/**
 * O vocabulario do etiquetador em portugues.
 *
 * O WD-Tagger so fala ingles: as etiquetas dele sao `forest`, `cloud`,
 * `no humans`. Os roteiros do Kintay sao em portugues, entao sem esta ponte a
 * busca por "floresta" nao acharia as 255 cenas de floresta que existem.
 *
 * Cada etiqueta traz os termos que ELE digitaria, nao a traducao literal:
 * "forest" vale por floresta, mata e bosque. Sem acento e minusculo, porque e
 * assim que a busca compara.
 *
 * Gerado uma vez a partir das 1536 etiquetas que aparecem na biblioteca dele
 * (3 cenas ou mais) e revisado a mao nas mais frequentes -- 58 entradas
 * corrigidas, 1414 aproveitadas como vieram. E um mapa FIXO no
 * repositorio, nao algo gerado na maquina de quem usa: errar aqui custa uma
 * busca que nao acha, e decidir isso em tempo de execucao custaria isso toda
 * vez.
 */
export const TAGS_PT: Readonly<Record<string, readonly string[]>> = {
  ":d": ["riso", "risadinha"],
  ":o": ["sorpresa", "surpresa"],
  "@ @": ["olho de dragao", "olho de lenda", "olho misterioso"],
  "^ ^": ["risada", "riso", "risadinha"],
  "1boy": ["um garoto", "menino", "homem"],
  "1girl": ["uma garota", "menina", "mulher"],
  "1other": ["outro"],
  "2boys": ["dois garotos", "dois meninos"],
  "2girls": ["duas garotas", "duas mulheres"],
  "2others": ["duas outras", "outros dois"],
  "3boys": ["tres garotos", "tres meninos"],
  "3girls": ["tres garotas", "tres mulheres", "tres meninas"],
  "4boys": ["quatro garotos"],
  "4girls": ["quatro garotas", "quatro mulheres"],
  "5boys": ["cinco garotos", "quintuplos", "meninos"],
  "5girls": ["cinco garotas", "quintuplas", "mulheres"],
  "6+boys": ["seis ou mais garotos", "seis ou mais meninos", "seis ou mais rapazes"],
  "6+girls": ["seis ou mais garotas", "mulheres em grupo"],
  "6+others": ["seis ou mais"],
  "above clouds": ["acima das nuvens"],
  "abs": ["abdomen"],
  "abstract": ["abstrato"],
  "adjusting eyewear": ["ajustando oculos"],
  "afloat": ["flutuando"],
  "afro": ["cabelo afro"],
  "age difference": ["diferenca de idade", "idade diferente"],
  "aged down": ["envelhecido", "velho"],
  "ahoge": ["afogando-se", "afogando"],
  "aiming": ["alinhando", "alvejando"],
  "air bubble": ["bolha de ar"],
  "aircraft": ["aviao"],
  "airplane": ["aviao"],
  "airship": ["navio aereo"],
  "alcohol": ["alcool"],
  "alien": ["alienigena", "extraterrestre"],
  "all fours": ["quatro patas"],
  "alley": ["ladeira", "rua estreita"],
  "alternate form": ["forma alternativa", "forma transformada"],
  "ambiguous gender": ["genero ambiguo"],
  "androgynous": ["androgino"],
  "android": ["robo"],
  "angel": ["anjo"],
  "angel wings": ["asas de anjo", "asas angelicais"],
  "anger vein": ["veia de raiva", "veia de furia", "veia de ira"],
  "angry": ["bravo", "raiva", "furioso"],
  "animal ear fluff": ["pelos das orelhas dos animais"],
  "animal ears": ["ouvidos de animal"],
  "animal focus": ["foco em animal", "animal", "animal focado"],
  "animal hood": ["capuz animal", "capuz de animal", "capuz mascote"],
  "animification": ["animacao", "transformacao"],
  "anklet": ["pulseira de tornozelo"],
  "antenna hair": ["cabelos antena"],
  "antennae": ["antenas", "antenas de inseto", "antenas de bug"],
  "apple": ["maca"],
  "apron": ["guarda-roupa"],
  "aqua eyes": ["olhos aqua", "olhos azul claro"],
  "aqua hair": ["cabelo aqua"],
  "aqua theme": ["tema aqua", "aqua"],
  "arch": ["arco"],
  "architecture": ["arquitetura"],
  "arm behind head": ["braco atras da cabeca"],
  "arm belt": ["cinto de braco"],
  "arm up": ["braco levantado", "braco erguido"],
  "arm wrap": ["faixa no braco", "braco envolto"],
  "armband": ["brinco de braco"],
  "armlet": ["bracalete", "bracete"],
  "armor": ["armadura"],
  "armored boots": ["botas de armadura", "botas de guerra"],
  "armpits": ["axilas"],
  "arms at sides": ["bracos ao lado", "bracos ao lado do corpo"],
  "arms behind back": ["bracos cruzados"],
  "arms behind head": ["bracos atras da cabeca"],
  "arms up": ["bracos levantados", "bracos acima da cabeca"],
  "ass": ["nao traduzivel"],
  "astronaut": ["astronauta"],
  "asymmetrical legwear": ["calcas assimetricas", "calcas desiguais"],
  "aura": ["energia"],
  "aurora": ["aurora boreal"],
  "autumn leaves": ["folhas de outono"],
  "axe": ["machado"],
  "baby": ["bebe", "crianca"],
  "back": ["costas"],
  "back-to-back": ["de costas um para o outro", "de costas"],
  "backlighting": ["iluminacao de fundo"],
  "backpack": ["mochila"],
  "bag": ["mochila"],
  "baggy pants": ["calcas soltas"],
  "bald": ["calvo", "cabelo ralo", "cabelo escasso"],
  "bamboo": ["bambu"],
  "bandage over one eye": ["faixa no olho", "faixa no olho unico"],
  "bandaged arm": ["braco vendado", "braco com curativo"],
  "bandaged head": ["cabeca vendada"],
  "bandaged leg": ["perna vendada"],
  "bandages": ["faixas"],
  "bandana": ["lenco de cabeca"],
  "banner": ["bandeira"],
  "bara": ["barra"],
  "bare pectorals": ["peito nu"],
  "bare shoulders": ["ombros descobertos", "ombros nus", "ombros a mostra"],
  "bare tree": ["arvore nua"],
  "barefoot": ["calcanhares descobertos"],
  "barrel": ["baril"],
  "baseball cap": ["bone de beisebol"],
  "baseball uniform": ["uniforme de beisebol"],
  "basket": ["carrinho", "cesta"],
  "bat wings": ["asas de morcego"],
  "bath": ["banho"],
  "bathing": ["banho"],
  "bathtub": ["banheira"],
  "battle": ["luta", "batalha"],
  "bdsm": ["dominacao", "submissao"],
  "beach": ["praia"],
  "bead necklace": ["colar de pingentes"],
  "beads": ["pingentes"],
  "beak": ["bico"],
  "beard": ["barba"],
  "bed": ["cama"],
  "bed sheet": ["lencol de cama"],
  "bedroom": ["quarto"],
  "beer mug": ["chopes", "mug de cerveja"],
  "bell": ["sinaleira"],
  "belt": ["cinto", "faixa"],
  "belt buckle": ["biqueira do cinto"],
  "bicycle": ["bicicleta"],
  "bikini": ["biquini"],
  "bikini top only": ["biquini top", "biquini so o top"],
  "bird": ["passaro"],
  "bird wings": ["as de passaro"],
  "black armor": ["armadura preta"],
  "black background": ["fundo preto"],
  "black belt": ["cinto preto", "cinto negro", "cinto de karate"],
  "black bikini": ["biquini preto"],
  "black border": ["borda preta", "borda negra"],
  "black bow": ["sete preto", "sete", "sete negro"],
  "black bowtie": ["gravata preta"],
  "black cape": ["capa preta", "capuz preto"],
  "black choker": ["colar preto", "choker preto"],
  "black cloak": ["capa preta"],
  "black coat": ["casaco preto", "paleto preto"],
  "black dress": ["vestido preto", "vestido escuro"],
  "black eyes": ["olhos pretos"],
  "black footwear": ["calcado preto"],
  "black gloves": ["luvas pretas", "luvas escuras"],
  "black hair": ["cabelo preto"],
  "black hairband": ["faixa preta no cabelo"],
  "black hakama": ["hakama preto", "roupa tradicional japonesa preta"],
  "black headband": ["faixa preta", "faixa de cabelo preta"],
  "black headwear": ["cabeca preta", "cabeca escura"],
  "black hoodie": ["hoodie preto"],
  "black horns": ["cornos pretos", "cornos escuros"],
  "black jacket": ["jaca preta"],
  "black kimono": ["kimono preto"],
  "black nails": ["unhas pretas"],
  "black necktie": ["gravata preta", "gravata negra"],
  "black panties": ["calcinhas pretas"],
  "black pants": ["calcas pretas", "calcas escuras"],
  "black pantyhose": ["calcinha preta"],
  "black ribbon": ["fitilho preto", "faixa preta"],
  "black robe": ["roba preta"],
  "black sclera": ["corneas pretas"],
  "black shirt": ["camisa preta"],
  "black shorts": ["shorts pretos"],
  "black skirt": ["saia preta"],
  "black sleeves": ["mangas pretas"],
  "black socks": ["meias pretas"],
  "black thighhighs": ["calcas de perna alta preta"],
  "black vest": ["jacket preta", "jacket", "jackets"],
  "black wings": ["asas pretas"],
  "blank eyes": ["olhos vazios", "olhos sem expressao"],
  "blanket": ["cobertor"],
  "blind": ["cego"],
  "blindfold": ["canga", "lenco-olho"],
  "blonde hair": ["cabelo loiro"],
  "blood": ["sangue", "sangrando"],
  "blood from eyes": ["sangue dos olhos", "sangue nos olhos"],
  "blood from mouth": ["sangue na boca", "boca com sangue"],
  "blood on clothes": ["sangue nas roupas"],
  "blood on face": ["sangue no rosto"],
  "blood on ground": ["sangue no chao", "sangue no solo"],
  "blood on hands": ["sangue nas maos"],
  "blood splatter": ["manchas de sangue"],
  "blue background": ["fundo azul", "fundo com azul", "azul"],
  "blue cape": ["capa azul"],
  "blue coat": ["casaco azul"],
  "blue dress": ["vestido azul"],
  "blue eyes": ["olhos azuis"],
  "blue fire": ["fogo azul"],
  "blue footwear": ["calcado azul", "sapatos azuis"],
  "blue hair": ["cabelo azul"],
  "blue jacket": ["jacket azul"],
  "blue pants": ["calcas azuis"],
  "blue rose": ["rosa azul"],
  "blue shirt": ["camisa azul"],
  "blue skin": ["pele azul"],
  "blue skirt": ["saia azul"],
  "blue sky": ["ceu azul"],
  "blue theme": ["tema azul"],
  "blunt bangs": ["cabelo de frente curto"],
  "blurry": ["desfocado", "borrado"],
  "blurry background": ["fundo borrado", "fundo embacado", "fundo desfocado"],
  "blurry foreground": ["plano de fundo borrado"],
  "blush": ["corado", "vermelho"],
  "blush stickers": ["pontinhos de rubor"],
  "boat": ["barco"],
  "bob cut": ["corte bob"],
  "bodysuit": ["traje de corpo inteiro"],
  "bokeh": ["fundo desfocado"],
  "bondage": ["ameaca sexual", "cativeiro"],
  "bone": ["osso"],
  "book": ["livro"],
  "book stack": ["pilha de livros"],
  "bookshelf": ["prateleira de livros"],
  "boots": ["botas"],
  "border": ["fronteira"],
  "bottle": ["garrafa"],
  "bound": ["amarrado", "atado"],
  "bouquet": ["arranjo-de-flores", "coroa-de-flores"],
  "bow": ["arco", "cinto"],
  "bow (weapon)": ["arco", "arco e flecha", "arqueiro"],
  "bowing": ["inclinando-se", "inclinando-se a cabeca"],
  "bowl": ["prato", "bacia"],
  "bowtie": ["gravata-borboleta"],
  "box": ["caixa"],
  "bracelet": ["bracelete"],
  "braid": ["tranca"],
  "braided ponytail": ["cabelo trancado"],
  "bread": ["pao"],
  "breaking": ["quebrando"],
  "breastplate": ["colete", "colete de armadura", "colete de guerra"],
  "breasts": ["mamas", "mamas grandes", "mamas volumosas"],
  "brick wall": ["parede de tijolo"],
  "bridal gauntlets": ["guantes nupciais"],
  "bridge": ["ponte", "passarela", "passagem"],
  "bright pupils": ["pupils claras", "pupils brilhantes", "olhos claros"],
  "broken": ["quebrado"],
  "broken glass": ["vidro quebrado", "fragmentos de vidro"],
  "broom": ["varredura", "vassoura"],
  "broom riding": ["montando varinha"],
  "brother and sister": ["irmao e irma", "irmaos", "irmaos e irmas"],
  "brothers": ["irmaos", "irmao"],
  "brown belt": ["cinto marrom", "cinto marron"],
  "brown cape": ["capa marrom"],
  "brown capelet": ["capa marrom"],
  "brown cloak": ["capa marrom", "capa marron"],
  "brown eyes": ["olhos marrons"],
  "brown footwear": ["calcado marron", "sapatos marrons"],
  "brown gloves": ["luvas marrons"],
  "brown hair": ["cabelo castanho"],
  "brown jacket": ["jacket marrom", "jacket marron", "jacket castanho"],
  "brown pants": ["calcas marrons"],
  "brown shirt": ["camisa marrom", "camisa marron", "camisa castanha"],
  "brown shorts": ["calcinhas marrons", "calcinhas marrom", "calcinhas de cor marrom"],
  "brown skirt": ["saia marrom"],
  "brown vest": ["jacket marrom"],
  "bruise": ["vazamento de sangue", "marrom"],
  "bruise on face": ["marcador no rosto"],
  "bubble": ["bolha"],
  "bucket": ["balde"],
  "bucket hat": ["chapeu de balde"],
  "buckle": ["biqueira", "biqueirada", "biqueiras"],
  "bug": ["inseto"],
  "building": ["predio"],
  "burning": ["queimando", "fumegante"],
  "bush": ["mato"],
  "butler": ["mordomo"],
  "butt crack": ["traseiro"],
  "butterfly": ["borboleta"],
  "buttons": ["botoes"],
  "buzz cut": ["corte buzz", "corte militar"],
  "cable": ["fio", "cabo"],
  "cactus": ["cacto"],
  "calendar (medium)": ["calendario (medio)"],
  "campfire": ["fogueira", "lareira de acampamento"],
  "candle": ["candelabro"],
  "candlelight": ["luz de vela", "luz de candelabro"],
  "candlestand": ["candelabro"],
  "cape": ["capa", "manto"],
  "capelet": ["capa", "capote"],
  "car": ["carro", "automovel", "veiculo"],
  "cardboard box": ["caixa de papelao"],
  "carpet": ["carpete", "tapete"],
  "carrying": ["carregando"],
  "casting spell": ["lancando feitico"],
  "castle": ["castelo"],
  "cat": ["gato"],
  "cat ears": ["ouvidos felinos"],
  "cat girl": ["garota gata", "gata humana"],
  "cat tail": ["cauda de gato"],
  "cave": ["cueva"],
  "ceiling": ["teto", "teto alto", "teto elevado"],
  "ceiling light": ["luz do teto", "luz de teto"],
  "chain": ["cadeado", "corrente"],
  "chair": ["cadeira", "poltrona"],
  "chaldea uniform": ["uniforme chaldea"],
  "chalkboard": ["quadro negro"],
  "chandelier": ["candelabro", "luzes", "luz"],
  "character name": ["nome do personagem"],
  "character profile": ["perfil do personagem"],
  "checkered floor": ["piso xadrez"],
  "cherry blossoms": ["cerejeiras em flor"],
  "chest tattoo": ["tatuagem no peito"],
  "chibi": ["personagem chibi", "personagem miniatura"],
  "child": ["crianca"],
  "chinese clothes": ["roupa chinesa"],
  "chinese text": ["texto chines", "letras chinesas"],
  "choker": ["colarinho"],
  "chopsticks": ["colheres de chino", "colheres de madeira", "colheres japonesas"],
  "christmas": ["natal"],
  "christmas tree": ["arvore de natal", "arvore", "natal"],
  "chromatic aberration": ["aberracao cromatica"],
  "church": ["igreja"],
  "city": ["cidade"],
  "city lights": ["iluminacao da cidade"],
  "cityscape": ["por do sol na cidade", "cena urbana"],
  "classroom": ["aula", "sala de aula", "aulas"],
  "claws": ["garras"],
  "cleavage": ["descoberta do peito", "descoberta do decote"],
  "cleavage cutout": ["decote generoso", "decote profundo"],
  "clenched hand": ["mao apertada", "mao cerrada"],
  "clenched hands": ["maos cerradas", "maos apertadas", "maos fechadas"],
  "clenched teeth": ["dentes cerrados"],
  "cliff": ["penhasco"],
  "cloak": ["capa"],
  "clock": ["relogio"],
  "close-up": ["close", "primeiro plano", "detalhe"],
  "closed eyes": ["olhos fechados"],
  "closed mouth": ["boca fechada", "serio"],
  "clothes hanger": ["varal de roupas"],
  "clothing cutout": ["corte na roupa", "abertura na roupa"],
  "cloud": ["nuvem", "nuvens"],
  "cloudy sky": ["ceu nublado"],
  "clown": ["carnaval"],
  "coat": ["casaco"],
  "collar": ["colar", "colarinho"],
  "collarbone": ["clavicula"],
  "collared shirt": ["camisa com colarinho"],
  "colored eyelashes": ["cilios coloridos"],
  "colored sclera": ["cornea colorida"],
  "colored skin": ["pele colorida", "pele com cor"],
  "colorful": ["colorido", "vibrante"],
  "column": ["coluna"],
  "column lineup": ["linha de colunas"],
  "comic": ["quadrinho", "desenho"],
  "completely nude": ["completamente nu"],
  "confetti": ["papel picado"],
  "constricted pupils": ["pupila contraida"],
  "convenient censoring": ["censoria conveniente", "censoramento facil"],
  "cooking": ["cozinhando"],
  "cooking pot": ["panela de cozinha"],
  "copyright name": ["nome de direitos autorais"],
  "corpse": ["cadaver"],
  "couch": ["poltrona"],
  "countdown": ["contagem regressiva"],
  "couple": ["cpl", "par"],
  "cousins": ["primos", "irmaos do segundo grau"],
  "cover": ["cobertura", "protecao"],
  "cover page": ["capa", "capa do livro", "capa do documento"],
  "covered eyes": ["olhos cobertos"],
  "covering own mouth": ["cobrindo a boca", "mexendo na boca"],
  "crack": ["fissura", "rachadura"],
  "cracked floor": ["piso quebrado"],
  "cracked wall": ["parede rachada"],
  "creature": ["ser", "monstro"],
  "credits": ["creditos"],
  "credits page": ["pagina de creditos"],
  "crescent": ["crescente"],
  "crescent moon": ["lua crescente"],
  "crop top": ["camiseta cropped"],
  "cross": ["cruz", "cruz religiosa"],
  "cross necklace": ["colar de cruz"],
  "cross-laced footwear": ["calcado lacrado com cruz", "sapatos lacrados com cruz"],
  "crossed arms": ["bracos cruzados"],
  "crossed bangs": ["cabelo na testa cruzado"],
  "crossed legs": ["pernas cruzadas", "pernas cruzadas em x"],
  "crossover": ["cross over"],
  "crow": ["corvo"],
  "crowd": ["multidao", "publico", "povo"],
  "crown": ["coroa"],
  "crown braid": ["cabelo com coroa", "coroa tranca"],
  "crying": ["chorando", "choro"],
  "crying with eyes open": ["chorando com os olhos abertos"],
  "crystal": ["cristal"],
  "cuffs": ["mangas", "mangas dobradas", "mangas do casaco"],
  "cup": ["copo", "xicara"],
  "curtained hair": ["cabelos com cortina"],
  "curtains": ["cortinas"],
  "dagger": ["daga"],
  "danmaku": ["comentario de tela", "comentario"],
  "dark": ["escuro", "escuridao"],
  "dark skin": ["pele escura", "cutis escuro", "cutis moreno"],
  "dark-skinned female": ["mulher morena"],
  "dark-skinned male": ["homem moreno", "homem com pele escura", "homem com cutis escuro"],
  "dated": ["antigo"],
  "day": ["dia", "diurno"],
  "death": ["morte", "falecimento"],
  "debris": ["escombros", "restos"],
  "demon boy": ["menino demonio", "garoto demonio"],
  "demon girl": ["garota demoniaca", "menina demoniaca"],
  "demon horns": ["cornos de demonio", "cornos"],
  "demon slayer uniform": ["uniforme do lutador contra demonios"],
  "demon tail": ["cauda de demonio", "cauda do demonio", "cauda maligna"],
  "demon wings": ["asas de demonio"],
  "depth of field": ["campo de profundidade"],
  "desert": ["deserto"],
  "desk": ["mesa de trabalho", "mesa", "escritorio"],
  "destruction": ["destruicao"],
  "detached sleeves": ["saias soltas", "saias separadas"],
  "dialogue box": ["caixa de dialogo"],
  "digimon (creature)": ["digimon", "criatura digimon"],
  "dirty": ["sujo", "suja"],
  "dog": ["cao"],
  "dog ears": ["ouvidos de cachorro", "ouvido de cachorro", "ouvido canino"],
  "doll joints": ["articulacoes de boneca"],
  "door": ["porta"],
  "double-breasted": ["paleto duplo-rebordado"],
  "dougi": ["objeto ritual"],
  "dragon": ["dragao"],
  "dragon girl": ["menina dragao", "dragao humanoide"],
  "dragon horns": ["chifres de dragao"],
  "dragon tail": ["cauda de dragao"],
  "dragon wings": ["asas de dragao"],
  "drawing bow": ["arco de desenho"],
  "dress": ["vestido"],
  "dress shirt": ["camisa social"],
  "drill hair": ["cabelo em ralacao", "cabelo em pente fino"],
  "drinking": ["bebendo"],
  "drinking glass": ["copo de bebida"],
  "drooling": ["salivacao", "salivando"],
  "dual persona": ["duas personalidades", "personalidade dupla"],
  "dual wielding": ["duas armas"],
  "duel": ["duelo", "luta"],
  "duel monster": ["monstro de duelo"],
  "dust": ["po", "polvo"],
  "dutch angle": ["angulo holandes"],
  "dwarf": ["anao"],
  "ear piercing": ["piercing de ouvido", "piercing auricular", "piercing do ouvido"],
  "earrings": ["pulseira", "brincos"],
  "earth (planet)": ["terra (planeta)"],
  "east asian architecture": ["arquitetura oriental"],
  "eating": ["comendo"],
  "elbow gloves": ["luvas de cotovelo"],
  "electricity": ["eletricidade"],
  "electrokinesis": ["eletricidade controlada"],
  "elf": ["elfo", "elfa"],
  "embers": ["cacos de madeira", "cacos de carvao"],
  "emphasis lines": ["linhas de enfase"],
  "energy": ["energia", "energia vital"],
  "energy ball": ["bola de energia"],
  "energy beam": ["raio de energia"],
  "energy sword": ["espada de energia"],
  "energy wings": ["asas de energia"],
  "english text": ["texto em ingles", "letras em ingles", "palavras em ingles"],
  "enmaided": ["vestida de enma", "vestida de noiva"],
  "envelope": ["maoila", "maoila japonesa", "maoila tradicional"],
  "everyone": ["todos", "toda a gente"],
  "evil grin": ["risada maligna", "risada malevola"],
  "evil smile": ["sorriso maligno", "sorriso malevolo"],
  "explosion": ["explosao"],
  "expressionless": ["sem expressao"],
  "extra arms": ["bracos extras", "bracos adicionais"],
  "extra eyes": ["olhos extras", "olhos adicionais"],
  "eye contact": ["olhar", "contato visual"],
  "eye focus": ["olhos em foco", "olhos focados"],
  "eye reflection": ["reflexo nos olhos"],
  "eyelashes": ["cilios"],
  "eyepatch": ["presa de olho", "cachecol de olho"],
  "eyeshadow": ["sombra de olho", "penumbra dos olhos"],
  "face-to-face": ["frente a frente", "de frente"],
  "faceless": ["sem rosto"],
  "facepaint": ["maquiagem facial"],
  "facial hair": ["barba", "bigode"],
  "facial mark": ["marca facial", "tatuagem facial", "sinal facial"],
  "facial tattoo": ["tatuagem facial"],
  "facing away": ["voltado para tras"],
  "facing viewer": ["facing o espectador", "facing o observador"],
  "fairy": ["fada"],
  "fairy (sao)": ["fada"],
  "fairy wings": ["asas de fada", "asas magicas", "asas encantadas"],
  "fake horns": ["hastes falsas", "cornos falsos"],
  "falling": ["caindo"],
  "family": ["familia", "parentes"],
  "fang": ["dente de vampiro", "dente afiado"],
  "fang out": ["dente de fora"],
  "fangs": ["caninos"],
  "fantasy": ["fantasia"],
  "fat": ["gordo", "obeso"],
  "fat man": ["homem gordo"],
  "father and daughter": ["pai e filha"],
  "father and son": ["pai e filho"],
  "feathered wings": ["asas de penas"],
  "feathers": ["plumas"],
  "feet": ["pes", "pe", "plantas dos pes"],
  "feet out of frame": ["pes fora do quadro"],
  "female pov": ["perspectiva feminina", "perspectiva de mulher"],
  "fence": ["muro", "cercado"],
  "field": ["campo"],
  "fiery hair": ["cabelo fogo", "cabelo ardente"],
  "fighting stance": ["posicao de luta", "posicao de combate"],
  "film grain": ["graos de filme"],
  "finger to mouth": ["dedo na boca"],
  "fingerless gloves": ["luvas sem dedos"],
  "fingernails": ["unhas", "unhas das maos"],
  "fire": ["fogo", "chamas"],
  "fireflies": ["larvas de fada", "fadas"],
  "fireplace": ["lareira", "chamine"],
  "fireworks": ["fogos de artificio"],
  "firing": ["disparando", "atirando"],
  "fish": ["peixe", "pescado"],
  "fish (food)": ["peixe (alimento)"],
  "fishing": ["pesca"],
  "fishing line": ["fio de pesca"],
  "fishing rod": ["canivete", "fishing knife"],
  "fishnets": ["rede de peixe", "rede de pescador"],
  "fist bump": ["troca de punhos"],
  "flag": ["bandeira"],
  "flat chest": ["peito plano"],
  "floating": ["flutuando"],
  "floating cape": ["capa flutuante", "capa voando", "capa levitando"],
  "floating hair": ["cabelo flutuante"],
  "floating rock": ["pedra flutuante"],
  "flower": ["flor"],
  "flower field": ["campo de flores", "campo florescente", "campo de flores coloridas"],
  "flower pot": ["pote de flor"],
  "flying": ["voo"],
  "flying sweatdrops": ["gotas de suor voando"],
  "fog": ["vapor", "nevoeiro"],
  "folding fan": ["ventilador dobravel"],
  "food": ["comida"],
  "food focus": ["foco em comida", "comida principal"],
  "food on face": ["comida na cara"],
  "foot focus": ["foco nos pes"],
  "footprints": ["passos", "chifres"],
  "forehead": ["frontal"],
  "forehead mark": ["marca no fronte", "tatuagem no fronte"],
  "forehead protector": ["protetor de testa", "protetor frontal"],
  "forehead-to-forehead": ["fronte a fronte"],
  "forest": ["floresta", "mata", "bosque"],
  "fork": ["garfo"],
  "formal": ["saudavel", "elegante"],
  "fountain": ["jato d'agua", "fonte"],
  "fox ears": ["ouvidos de raposa", "ouvido de raposa"],
  "fox mask": ["mascara de raposa", "mascara de rosto"],
  "fox tail": ["cauda de raposa"],
  "freckles": ["macacao", "manchas de nascenca"],
  "frills": ["fivelas", "ornamentos"],
  "from above": ["de cima"],
  "from behind": ["de costas"],
  "from below": ["de baixo", "abaixo"],
  "from outside": ["de fora"],
  "from side": ["de lado"],
  "front-tie bikini top": ["top de biquini com no na frente", "biquini com no na frente"],
  "front-tie top": ["camisa de gola frontal", "camisa de tiras", "camisa de tiras na frente"],
  "frown": ["ar de tristeza", "ar de insatisfacao"],
  "fruit": ["fruta", "frutas"],
  "full armor": ["armadura completa"],
  "full body": ["corpo inteiro", "cuerpo inteiro"],
  "full moon": ["lua cheia"],
  "fur collar": ["colarinho de pelo"],
  "fur hat": ["chapeu de pele"],
  "fur scarf": ["lenco de pelo"],
  "fur trim": ["acessorio de pele"],
  "fur-trimmed capelet": ["capa com bordas de pelo"],
  "fur-trimmed coat": ["casaco com borda de pele"],
  "fur-trimmed jacket": ["jacket com pelagem", "jacket com pelo"],
  "fur-trimmed sleeves": ["saias de pelo", "saias de pelucia", "pelucia"],
  "furry": ["peludo", "felpudo"],
  "furry male": ["homem peludo"],
  "gae bolg (fate)": ["gae bolg", "fate"],
  "gakuran": ["gakuran uniforme"],
  "galaxy": ["galaxia"],
  "gameplay mechanics": ["mecanicas de jogo"],
  "garreg mach monastery uniform": ["uniforme do monasterio garreg mach"],
  "gauntlets": ["guantelete", "guantelete de metal"],
  "gears": ["engrenagens"],
  "gem": ["pedra preciosa", "joia"],
  "genderswap (ftm)": ["genero feminino"],
  "giant": ["gigante"],
  "gift": ["presente"],
  "glass": ["vidro"],
  "glasses": ["lentes"],
  "glitch": ["erro", "bug"],
  "gloves": ["luvas"],
  "glowing": ["brilhando", "brilho"],
  "glowing eye": ["olho brilhante", "olho reluzente"],
  "glowing eyes": ["olhos brilhantes", "olhos reluzentes", "olhos luminosos"],
  "glowing hair": ["cabelo brilhante", "cabelo reluzente"],
  "glowing sword": ["espada brilhante"],
  "glowing weapon": ["arma brilhante"],
  "glowing wings": ["asas brilhantes"],
  "goatee": ["bigode"],
  "goatee stubble": ["bigode", "barba"],
  "goggles": ["luvas de mergulho", "protecao oculares", "luvas de oculos"],
  "goggles around neck": ["lentes de mergulho ao redor do pescoco"],
  "goggles on head": ["lentes de mergulho na cabeca"],
  "gold armor": ["armadura dourada"],
  "gothic lolita": ["loleita gotica", "loleite gotica"],
  "grabbing": ["agarrando", "pegando"],
  "gradient background": ["fundo gradiente"],
  "grand piano": ["piano grande"],
  "grapes": ["uvas", "uva", "morangos"],
  "grass": ["grama", "campo"],
  "green background": ["fundo verde", "fundo com verde", "verde"],
  "green cape": ["capa verde", "capuz verde"],
  "green cloak": ["capa verde", "capa com verde", "verde"],
  "green dress": ["vestido verde"],
  "green eyes": ["olhos verdes"],
  "green footwear": ["calcado verde", "sapatos verdes"],
  "green gemstone": ["pedra verde"],
  "green hair": ["cabelo verde", "cabelo com tons verdes"],
  "green hairband": ["faixa de cabelo verde"],
  "green headwear": ["cabeleira verde"],
  "green jacket": ["jacket verde", "jacket vermelho", "jacket verde escura"],
  "green pants": ["calcas verdes"],
  "green shirt": ["camisa verde"],
  "green skin": ["pele verde"],
  "green theme": ["tema verde"],
  "grey background": ["fundo cinza"],
  "grey border": ["borda cinza"],
  "grey eyes": ["olhos cinzentos", "olhos cinza"],
  "grey footwear": ["calcado cinza"],
  "grey hair": ["cabelo cinza"],
  "grey pants": ["calcas cinzentas"],
  "grey shirt": ["camisa cinza"],
  "grey skin": ["pele cinza", "pele grisalha"],
  "grey sky": ["ceu cinza"],
  "greyscale": ["escala de cinza", "preto e branco"],
  "grin": ["risada", "riso"],
  "gun": ["arma de fogo", "revolver"],
  "habit": ["veste religiosa"],
  "hair bell": ["sinaleira no cabelo"],
  "hair between eyes": ["cabelo no meio do rosto", "cabelo entre os olhos"],
  "hair bow": ["faixa de cabelo"],
  "hair bun": ["coque de cabelo", "coque de cabelo alto", "coque de cabelo tradicional"],
  "hair flower": ["flores no cabelo"],
  "hair intakes": ["fios de cabelo", "cabelo preso", "cabelo em trancas"],
  "hair ornament": ["adorno de cabelo", "acessorio de cabelo", "pulseira de cabelo"],
  "hair over eyes": ["cabelos nos olhos"],
  "hair over one eye": ["cabelo cobrindo um olho"],
  "hair over shoulder": ["cabelo caindo no ombro", "cabelo caindo", "cabelo no ombro"],
  "hair pulled back": ["cabelo preso"],
  "hair ribbon": ["faixa de cabelo", "faixa de cabelo colorida", "faixa de cabelo decorativa"],
  "hair rings": ["anel de cabelo", "anel no cabelo"],
  "hair slicked back": ["cabelo para tras", "cabelo preso para tras"],
  "hair stick": ["pregador de cabelo"],
  "hair tubes": ["canaletas de cabelo"],
  "hair up": ["cabelo para cima", "cabelo preso"],
  "hairband": ["faixa no cabelo"],
  "hairclip": ["penteado", "pincoleta"],
  "hairpin": ["pregador de cabelo"],
  "hakama": ["calca hakama"],
  "hakama skirt": ["short hakama", "hakama saia"],
  "half mask": ["metade do rosto coberta"],
  "half updo": ["meio coque", "corte meio solto", "corte meio preso"],
  "half-closed eyes": ["olhos meio fechados"],
  "hallway": ["corredor"],
  "halo": ["circulo de luz", "aura"],
  "hammer": ["martelo"],
  "hand fan": ["ventilador de mao"],
  "hand focus": ["foco manual"],
  "hand on another's head": ["mao no cabelo de outra pessoa"],
  "hand on another's shoulder": ["mao no ombro de outra pessoa"],
  "hand on own cheek": ["mao no rosto", "tocando no rosto", "rosto coberto"],
  "hand on own chest": ["mao no peito", "peito", "tocando peito"],
  "hand on own chin": ["mao na barba", "mao no queixo"],
  "hand on own face": ["mao no rosto"],
  "hand on own head": ["mao no proprio cabeca"],
  "hand on own hip": ["mao no quadril", "mao no lado"],
  "hand up": ["mao levantada", "mao erguida"],
  "hands in opposite sleeves": ["maos em mangas opostas"],
  "hands in pockets": ["maos nas bolsas", "maos nos bolsos"],
  "hands on own face": ["mao na cara", "maos na cara"],
  "hands on own head": ["maos na propria cabeca"],
  "hands on own hips": ["maos nos quadris"],
  "hands up": ["maos levantadas", "maos acima", "maos erguidas"],
  "hanfu": ["roupa tradicional chinesa"],
  "hanging breasts": ["mamas penduradas"],
  "haori": ["casaco tradicional japones"],
  "hat": ["chapeu"],
  "head out of frame": ["cabeca fora da tela", "cabeca fora do quadro", "cabeca fora da imagem"],
  "head rest": ["base de cabeca"],
  "headband": ["faixa no cabelo"],
  "headpat": ["puxao de ouvido", "puxao de cabelo"],
  "headphones": ["fones de ouvido"],
  "heads together": ["cabecas juntas"],
  "heart": ["coracao"],
  "heart hair ornament": ["adorno de cabelo no formato de coracao"],
  "heart-shaped pupils": ["pupila em forma de coracao"],
  "helmet": ["chapeu de motociclista", "capuz"],
  "hetero": ["heterossexual"],
  "heterochromia": ["olhos de diferentes cores", "olhos com cores diferentes"],
  "high collar": ["colar alto", "colar elevado"],
  "high heel boots": ["botas de salto alto"],
  "high heels": ["calcados altos", "salto alto"],
  "high ponytail": ["coque alto"],
  "hill": ["colina"],
  "hime cut": ["corte de princesa", "corte princesa", "corte de cabelo princesa"],
  "hogwarts school uniform": ["uniforme da hogwarts", "uniforme da escola de magia e bruxaria"],
  "holding": ["segurando"],
  "holding animal": ["segurando animal", "com animal"],
  "holding axe": ["segurando facao", "com facao"],
  "holding book": ["segurando livro", "com livro"],
  "holding bow (weapon)": ["segurando arco", "arco e flecha"],
  "holding chopsticks": ["segurando colheres de chino"],
  "holding clothes": ["segurando roupas"],
  "holding cup": ["segurando copo", "copo nas maos"],
  "holding envelope": ["segurando envelope"],
  "holding fan": ["segurando um ventilador"],
  "holding fishing rod": ["segurando vara de pesca", "com vara de pesca"],
  "holding food": ["comendo", "pegando comida"],
  "holding fruit": ["segurando fruta"],
  "holding gun": ["segurando arma", "arma", "pistola"],
  "holding hands": ["segurando maos", "maos unidas"],
  "holding hat": ["segurando chapeu", "chapeu", "chapeus"],
  "holding jewelry": ["segurando joias"],
  "holding knife": ["segurando faca"],
  "holding letter": ["segurando carta"],
  "holding mask": ["segurando mascara"],
  "holding necklace": ["segurando pulseira", "segurando colar"],
  "holding paper": ["segurando papel", "com papel"],
  "holding polearm": ["segurando arma de assalto"],
  "holding shield": ["segurando escudo", "escudo em maos"],
  "holding spoon": ["segurando colher", "colher", "colheres"],
  "holding staff": ["segurando bastao"],
  "holding sword": ["segurando espada", "com espada", "espada na mao"],
  "holding umbrella": ["segurando guarda-chuva"],
  "holding weapon": ["segurando arma"],
  "hood": ["capuz", "capuz do casaco", "capuz do jaqueta"],
  "hood down": ["capuz abaixado"],
  "hood up": ["capuz levantado"],
  "hooded cloak": ["capa com capuz"],
  "hoop earrings": ["ouviras de anel", "ouviras circulares", "ouviras de anel de metal"],
  "horizon": ["horizonte"],
  "horned helmet": ["capacete com chifres", "capacete chifrado"],
  "horns": ["chifres"],
  "horror (theme)": ["terror"],
  "horse": ["cavalo"],
  "horse ears": ["ouvidos de cavalo"],
  "horse girl": ["garota cavalo"],
  "horseback riding": ["cavaleiro"],
  "house": ["casa"],
  "how to": ["como", "instrucoes"],
  "hug": ["abraco"],
  "huge weapon": ["arma gigante", "arma enorme"],
  "hugging own legs": ["abrindo pernas", "pernas abertas"],
  "husband and wife": ["esposo e esposa", "conjuge", "conjuges"],
  "ice": ["gelo"],
  "implied kiss": ["beijo implicito", "beijo sugerido", "beijo sutil"],
  "index finger raised": ["dedo indicador levantado"],
  "indian style": ["estilo indiano"],
  "indoors": ["dentro", "interior", "ambiente interno"],
  "injury": ["lesao", "ferida"],
  "inkwell": ["tinteiro", "tinta"],
  "instrument": ["instrumento", "instrumento musical"],
  "interlocked fingers": ["dedos entrelacados"],
  "jacket": ["casaco"],
  "jacket on shoulders": ["jacket nas costas"],
  "japanese clothes": ["roupas japonesas"],
  "jewelry": ["joias"],
  "jingle bell": ["sinaleira que toca"],
  "joints": ["articulacoes"],
  "juliet sleeves": ["saias de juliet"],
  "jumping": ["pulando", "salto"],
  "karate gi": ["roupa de karate"],
  "katana": ["espada katana"],
  "kicking": ["chutando"],
  "kimono": ["roupa japonesa"],
  "kiss": ["beijo", "beijo apaixonado"],
  "knee boots": ["botas de joelho"],
  "kneehighs": ["calcas de joelho", "calcas joelho"],
  "kneeling": ["joelhando"],
  "knife": ["facao", "navio"],
  "knight": ["cavaleiro"],
  "konohagakure symbol": ["simbolo de konohagakure", "simbolo de vila oculta da folha", "simbolo ninja"],
  "korean text": ["texto coreano"],
  "lab coat": ["blusa de laboratorio"],
  "lake": ["lago"],
  "lamp": ["luz", "lampada"],
  "lamppost": ["pilhavete"],
  "landscape": ["paisagem"],
  "lantern": ["lanterna"],
  "large breasts": ["mamas grandes", "mamas volumosas"],
  "large pectorals": ["musculos do peito grandes", "musculos grandes", "musculos do peito"],
  "large wings": ["asas grandes"],
  "laughing": ["rindo"],
  "layered sleeves": ["mangas camadas"],
  "leaf": ["folha"],
  "legs": ["pernas"],
  "lemon": ["limao"],
  "lemon slice": ["fatia de limao"],
  "lens flare": ["reflexo de lente", "reflexo de lente de camera"],
  "leotard": ["leotardo"],
  "letter": ["carta", "lavra", "mensage"],
  "letterboxed": ["faixa preta", "cinematografico"],
  "library": ["biblioteca", "sala de livros"],
  "licking": ["lambendo"],
  "light": ["luz"],
  "light blue hair": ["cabelo azul claro", "cabelo celeste claro"],
  "light brown hair": ["cabelo castanho claro"],
  "light particles": ["particulas de luz", "brilhos"],
  "light rays": ["raios de luz"],
  "lightning": ["raio", "fulgor", "relampago"],
  "lightsaber": ["espada laser", "espada de luz"],
  "lion": ["leao", "regio", "feroz"],
  "lion ears": ["ouvidos de leao"],
  "lipstick": ["batom"],
  "log": ["tronco", "madeira"],
  "logo": ["logotipo", "marca"],
  "lolita fashion": ["loleita", "loleite"],
  "long beard": ["barba longa"],
  "long coat": ["casaco longo"],
  "long hair": ["cabelo longo"],
  "long skirt": ["saia longa"],
  "long sleeves": ["cabelos longos", "bracos cobertos"],
  "looking at another": ["olhando para outro", "olhando para alguem", "olhando para alguem de lado"],
  "looking at viewer": ["olhando para a camera", "encarando"],
  "looking back": ["olhando para tras", "vendo para tras"],
  "looking down": ["olhando para baixo", "olhando para o chao"],
  "looking to the side": ["olhando de lado", "olhando lateralmente", "lateralmente"],
  "looking up": ["olhando para cima", "levantando os olhos"],
  "lotus": ["loto", "flores de loto", "lilium"],
  "low ponytail": ["cabelo preso em rabo de cavalo baixo"],
  "low-tied long hair": ["cabelo longo preso baixo", "cabelo preso baixo"],
  "lower body": ["parte inferior do corpo", "pernas"],
  "lower teeth only": ["dentes inferiores"],
  "lying": ["deitado", "sentado no chao"],
  "mage staff": ["bastao de mago"],
  "magic": ["magia", "feitico"],
  "magic circle": ["circulo magico"],
  "magical girl": ["garota magica"],
  "maid": ["empregada", "empregada domestica"],
  "maid apron": ["apron de empregada", "apron de empregada domestica"],
  "maid headdress": ["chicote de empregada", "cabeleira de empregada"],
  "makeup": ["maquiagem"],
  "male focus": ["homem", "rapaz", "garoto"],
  "manly": ["masculino"],
  "map": ["mapa"],
  "maple leaf": ["folha de outono", "folha de carvalho"],
  "mask": ["mascara", "cara tapada", "mascara facial"],
  "mature male": ["homem maduro", "homem adulto"],
  "meat": ["carne", "proteina", "carnes"],
  "medium breasts": ["mamas medias", "mamas de tamanho medio"],
  "medium hair": ["cabelo medio"],
  "meme": ["memes"],
  "metal collar": ["collar metalico", "collar de metal"],
  "microphone": ["microfone"],
  "midriff": ["pancada", "pancinha"],
  "military": ["militar", "exercito"],
  "military uniform": ["uniforme militar", "traje militar"],
  "military vehicle": ["veiculo militar"],
  "milky way": ["via lactea", "galaxia de leite", "caminho do leite"],
  "mini crown": ["coroa pequena", "diadema"],
  "mini hat": ["chapeu pequeno"],
  "mini person": ["personagem miniatura", "personagem pequeno", "personagem chibi"],
  "minigirl": ["garotinha", "crianca", "pequena garota"],
  "mirror": ["espelho"],
  "mixed-language text": ["texto em varias linguas"],
  "mob cap": ["chapeu de xarope"],
  "mohawk": ["cabelo em corneta"],
  "mole": ["mancha"],
  "mole under eye": ["mancha debaixo do olho"],
  "monk": ["monge"],
  "monochrome": ["preto e branco", "monocromatico"],
  "monocle": ["lente monoculinar", "lente unica"],
  "monster": ["monstro"],
  "monster girl": ["menina monstro", "criatura feminina"],
  "moon": ["lua"],
  "moonlight": ["luz da lua", "lua"],
  "moss": ["mossas"],
  "mother and daughter": ["mae e filha"],
  "mother and son": ["mae e filho"],
  "motion blur": ["borramento de movimento"],
  "motor vehicle": ["veiculo motorizado"],
  "mountain": ["montanha"],
  "mountainous horizon": ["horizonte montanhoso", "horizonte com montanhas"],
  "mouth mask": ["mascara na boca"],
  "mug": ["cha", "cafe", "xicara"],
  "multi-tied hair": ["cabelo preso em varios lugares"],
  "multicolored hair": ["cabelo multicolorido"],
  "multiple boys": ["varios homens", "grupo"],
  "multiple girls": ["varias mulheres", "grupo"],
  "multiple others": ["varios outros"],
  "multiple swords": ["multiplas espadas"],
  "multiple tails": ["caudas multiplas"],
  "multiple wings": ["varias asas", "asas multiplas"],
  "mummy": ["mummificacao"],
  "muscular": ["muscoso"],
  "muscular male": ["homem musculoso", "homem forte", "homem atletico"],
  "music": ["musica", "melodia", "sonido"],
  "mustache": ["bigode"],
  "nail polish": ["esmalte nas unhas"],
  "nature": ["natureza"],
  "navel": ["ombro"],
  "nebula": ["nebulosa"],
  "neck ribbon": ["lenco no pescoco", "lenco ao redor do pescoco", "lenco do pescoco"],
  "necklace": ["colar"],
  "necktie": ["gravata"],
  "negative space": ["espaco negativo", "espaco vazio"],
  "newspaper": ["jornal"],
  "night": ["noite", "noturno"],
  "night sky": ["ceu noturno", "noite estrelada", "ceu de noite"],
  "nightgown": ["camisola", "vestido de noite"],
  "nipples": ["mamas"],
  "no humans": ["sem pessoas", "cenario vazio", "sem ninguem"],
  "no mouth": ["sem boca"],
  "no pupils": ["sem pupilas", "sem olhos", "olhos vazios"],
  "nosebleed": ["sangramento nasal", "sangramento do nariz", "sangramento na nariz"],
  "nude": ["nu", "naked"],
  "nun": ["freira"],
  "o-ring": ["anel o"],
  "obi": ["cinto japones", "cinto tradicional japones", "cinto kimono"],
  "object on head": ["objeto na cabeca"],
  "ocean": ["oceano", "mar"],
  "off shoulder": ["quase nas costas"],
  "off-shoulder dress": ["vestido decote nas costas"],
  "official style": ["estilo oficial", "estilo padrao", "estilo formal"],
  "old": ["velho", "antigo", "veterano"],
  "old man": ["velho"],
  "old woman": ["vovo", "avo"],
  "on back": ["nas costas"],
  "on bed": ["na cama", "em cima da cama"],
  "on chair": ["na cadeira"],
  "on couch": ["no sofa"],
  "on floor": ["no chao", "em cima do chao"],
  "on ground": ["no chao"],
  "on one knee": ["de joelhos"],
  "on shoulder": ["no ombro"],
  "on side": ["lado", "lateral", "lado a lado"],
  "on stomach": ["no ventre"],
  "one eye closed": ["olho fechado", "um olho fechado"],
  "one eye covered": ["olho coberto"],
  "oni": ["demonio japones"],
  "onsen": ["banho quente japones"],
  "opaque glasses": ["lentes escurecidas"],
  "open book": ["livro aberto"],
  "open clothes": ["roupa aberta", "roupa desabotoada"],
  "open coat": ["casaco aberto"],
  "open jacket": ["jacket aberto"],
  "open mouth": ["boca aberta", "gritando"],
  "open shirt": ["camisa aberta", "manga levantada"],
  "orange belt": ["cinto laranja"],
  "orange cape": ["capa laranja", "capa de cetim"],
  "orange eyes": ["olhos laranja"],
  "orange flower": ["flor laranja"],
  "orange hair": ["cabelo laranja", "cabelo naranja", "cabelo dourado"],
  "orange jacket": ["jacket amarelo", "jacket laranja", "jacket de manga comprida"],
  "orange pants": ["calcas laranja"],
  "orange scarf": ["lenco laranja"],
  "orange sky": ["ceu laranja"],
  "orange theme": ["tema laranja"],
  "orb": ["esfera"],
  "other focus": ["outro foco"],
  "otoko no ko": ["menino de garrafa"],
  "out of frame": ["fora da tela"],
  "outdoors": ["ao ar livre", "externa", "rua"],
  "outstretched arm": ["braco estendido"],
  "outstretched arms": ["bracos estendidos", "bracos abertos"],
  "outstretched hand": ["mao estendida", "maos estendidas"],
  "over shoulder": ["por cima do ombro"],
  "overcast": ["nuvens", "nuvens carregadas", "nuvens densas"],
  "overgrown": ["sobrando"],
  "own hands clasped": ["maos juntas", "maos entrelacadas"],
  "own hands together": ["proprias maos juntas"],
  "painting (object)": ["pintura", "quadro"],
  "pajamas": ["pijamas"],
  "pale skin": ["pele palida"],
  "palms": ["palmas"],
  "panties": ["cueiro"],
  "panties on head": ["cueiros na cabeca", "calcinhas na cabeca"],
  "pants": ["calcas"],
  "pantyhose": ["meias-calcas"],
  "paper": ["papel"],
  "paper bag": ["sacola de papel"],
  "paper lantern": ["lanterna de papel", "lanterna japonesa", "lanterna de festa"],
  "parted bangs": ["cabelo na testa preso"],
  "parted lips": ["labios separados", "labios abertos", "labios sorridentes"],
  "partially fingerless gloves": ["luvas sem dedos", "luvas parcialmente sem dedos"],
  "partially submerged": ["submerso parcialmente"],
  "path": ["caminho"],
  "pauldrons": ["pausdrons"],
  "pectoral cleavage": ["decote generoso", "decote pronunciado"],
  "peeking out": ["saindo", "aparecendo"],
  "pen": ["caneta"],
  "people": ["pessoas"],
  "personification": ["personagem", "representacao"],
  "petals": ["petalas", "florescencia"],
  "phone": ["celular"],
  "photo background": ["fundo da foto"],
  "piercing": ["punching", "punch", "furto"],
  "piggyback": ["carregando nas costas"],
  "pillar": ["pilastro", "pilar", "coluna"],
  "pillow": ["travesseiro"],
  "pinching": ["apanhando", "segurando", "preensando"],
  "pine tree": ["pinheiro"],
  "pink background": ["fundo rosa", "fundo pink"],
  "pink bow": ["laco rosa", "laco pink"],
  "pink dress": ["vestido rosa"],
  "pink eyes": ["olhos rosa"],
  "pink flower": ["flor rosa", "flor pink"],
  "pink footwear": ["calcado rosa"],
  "pink hair": ["cabelo rosa"],
  "pink ribbon": ["faixa rosa"],
  "pink rose": ["rosa rosa"],
  "pink theme": ["tema rosa", "tema pink", "cor rosa"],
  "planet": ["planeta", "estrela"],
  "plant": ["planta"],
  "planted": ["plantado"],
  "planted sword": ["espada plantada"],
  "plate": ["prato"],
  "playing instrument": ["tocando instrumento"],
  "pleated skirt": ["saia plissada"],
  "plugsuit": ["traje de plugsuit"],
  "pointing": ["apontando"],
  "pointy ears": ["ouvidos pontudos"],
  "pokemon (creature)": ["pokemon", "criatura", "monstro"],
  "polearm": ["arma de asta"],
  "ponytail": ["cabelo preso", "cabelo rabo de cavalo"],
  "pool of blood": ["lago de sangue"],
  "portrait": ["retrocesso", "retro"],
  "potted plant": ["planta em vasos"],
  "pouch": ["bolso", "cinto"],
  "pout": ["biquinho", "cara de descontentamento"],
  "pov": ["ponto de vista"],
  "pov hands": ["maos na perspectiva do personagem"],
  "power lines": ["fios de energia"],
  "praying": ["orando", "rezando"],
  "priest": ["padre", "sacerdote", "sacerdotisas"],
  "princess carry": ["carrinho de princesa", "carrinho infantil"],
  "profile": ["perfil"],
  "psychic": ["psiquico", "psicopata"],
  "puffy sleeves": ["mangas arredondadas", "mangas volumosas"],
  "purple background": ["fundo roxo"],
  "purple dress": ["vestido roxo", "roupa roxa"],
  "purple eyes": ["olhos roxos", "olhos violaceos", "olhos lilases"],
  "purple fire": ["fogo roxo"],
  "purple flower": ["flor roxa"],
  "purple hair": ["cabelo roxo"],
  "purple headwear": ["cabeca roxa", "cabeleira roxa"],
  "purple jacket": ["jacket roxo", "jacket violaceo"],
  "purple lips": ["labios roxos"],
  "purple nails": ["unhas roxas"],
  "purple pants": ["calcas roxas", "calcas violaceas"],
  "purple ribbon": ["faixa roxa"],
  "purple shirt": ["camisa roxa"],
  "purple skin": ["pele roxa"],
  "purple sky": ["ceu roxo"],
  "purple theme": ["tema roxo", "roxo", "cor roxa"],
  "quill": ["pluma"],
  "quiver": ["arco", "arqueiro"],
  "rabbit ears": ["ouvidos de coelho"],
  "raglan sleeves": ["mangas raglan"],
  "railing": ["barra de apoio", "guarda-corpo"],
  "rain": ["chuva", "chovendo"],
  "rainbow": ["arco-iris"],
  "reaching": ["estendendo", "alcancando"],
  "reading": ["lendo"],
  "red background": ["fundo vermelho"],
  "red border": ["borda vermelha"],
  "red bow": ["fita vermelha"],
  "red bowtie": ["gravata vermelha"],
  "red cape": ["capa vermelha"],
  "red capelet": ["capuz vermelho", "capa vermelha"],
  "red carpet": ["carpete vermelho", "carpete", "vermelho"],
  "red curtains": ["cortinas vermelhas"],
  "red dress": ["vestido vermelho"],
  "red eyes": ["olhos vermelhos"],
  "red eyeshadow": ["sombra de olho vermelha"],
  "red flower": ["flor vermelha"],
  "red footwear": ["calcado vermelho"],
  "red hair": ["cabelo ruivo"],
  "red hakama": ["hakama vermelho", "hakama", "hakamas"],
  "red jacket": ["jacket vermelho", "jacket vermelha", "blusa vermelha"],
  "red kimono": ["kimono vermelho"],
  "red leotard": ["leotard vermelho"],
  "red lips": ["labios vermelhos", "labios rosados", "labios corados"],
  "red necktie": ["gravata vermelha"],
  "red pants": ["calcas vermelhas", "calcas de treino vermelhas"],
  "red ribbon": ["faixa vermelha"],
  "red scarf": ["lenco vermelho", "lenco de cor vermelha"],
  "red shirt": ["camisa vermelha", "camiseta vermelha"],
  "red shorts": ["calcinhas vermelhas", "shorts vermelhos"],
  "red skin": ["pele vermelha"],
  "red skirt": ["saia vermelha"],
  "red sky": ["ceu vermelho"],
  "red theme": ["tema vermelho", "vermelho"],
  "red vest": ["jacket vermelha", "blusa vermelha", "camisa vermelha"],
  "reflection": ["reflexo"],
  "ribbon": ["fitilho"],
  "ribbon trim": ["faixa de bordado"],
  "ribbon-trimmed sleeves": ["mangas com fitas", "mangas com lacos"],
  "rice": ["arroz"],
  "riding": ["montando", "cavalo"],
  "rifle": ["fuzil"],
  "ring": ["anel"],
  "ripples": ["marolas"],
  "river": ["rio", "corrente", "ravine"],
  "road": ["estrada"],
  "robe": ["roba"],
  "robot": ["robo"],
  "rock": ["pedra"],
  "roman numeral": ["numeral romano"],
  "rooftop": ["teto", "telhado", "cimo do telhado"],
  "rope": ["corda"],
  "rose": ["rosa"],
  "roswaal mansion maid uniform": ["uniforme de empregada da mansao roswaal"],
  "round eyewear": ["lentes redondas"],
  "rubble": ["escombros"],
  "rug": ["carpetinha", "carpete", "tapete"],
  "ruins": ["ruinas"],
  "running": ["correndo"],
  "rural": ["vila", "campo"],
  "sad": ["triste"],
  "sailor collar": ["colarinho marinheiro"],
  "sailor moon redraw challenge (meme)": ["desafio sailor moon", "sailor moon redesenhado"],
  "sand": ["areia"],
  "sandals": ["sandalia"],
  "sarashi": ["faixa", "faixa de luta", "faixa de combate"],
  "sash": ["faixa", "faixa de seda"],
  "saucer": ["prato pequeno", "saque"],
  "scales": ["espaldares", "escamas", "escamas de dragao"],
  "scar": ["cicatriz", "ferida"],
  "scar across eye": ["cicatriz no olho"],
  "scar on cheek": ["cicatriz no rosto", "cicatriz", "cicatrizes"],
  "scar on face": ["cicatriz no rosto"],
  "scared": ["assustado", "medo"],
  "scarf": ["lenco"],
  "scene reference": ["referencia de cena"],
  "scenery": ["cenario", "paisagem", "plano aberto"],
  "school uniform": ["uniforme escolar"],
  "science fiction": ["ficcao cientifica"],
  "screaming": ["gritando"],
  "scythe": ["foice"],
  "see-through": ["transparente", "translucido"],
  "seiza": ["sentado em seiza"],
  "semi-rimless eyewear": ["lentes sem montura"],
  "sepia": ["marrom escuro", "tonalidade marrom"],
  "serafuku": ["uniforme de serafim", "uniforme celestial", "uniforme de anjo"],
  "serious": ["serio", "triste"],
  "shaded face": ["rosto sombreado", "rosto com sombra"],
  "shadow": ["sombra"],
  "shards": ["fragmentos"],
  "sharp teeth": ["dentes afiados"],
  "shawl": ["lenco"],
  "sheath": ["cinto"],
  "sheathed": ["embainhada", "embainhado"],
  "shelf": ["prateleira"],
  "shield": ["escudo"],
  "shinai": ["espada de bambu", "espada de treino"],
  "ship": ["navio"],
  "shirt": ["camisa"],
  "shoelaces": ["fivelas", "cordoes"],
  "shoes": ["calcados", "sapatos"],
  "shooting star": ["estrela cadente"],
  "short bangs": ["cabelo de lado curto"],
  "short hair": ["cabelo curto"],
  "short hair with long locks": ["cabelo curto com mechas longas"],
  "short over long sleeves": ["saiu curto por cima de manga longa"],
  "short ponytail": ["cabelo curto preso", "cabelo preso curto"],
  "short shorts": ["calcas curtas"],
  "short sleeves": ["bracos descobertos", "bracos sem manga"],
  "short twintails": ["cabelos em duas caudas curtas"],
  "shorts": ["calcas curtas"],
  "shouji": ["porta-japonesa"],
  "shoulder armor": ["armadura de ombro"],
  "shoulder cutout": ["corte nas costas"],
  "shoulder pads": ["pudim de ombro", "pudim nas costas"],
  "shoulder spikes": ["picos nos ombros"],
  "shouting": ["gritando", "gritando alto", "gritando forte"],
  "shrine": ["santuario", "templo"],
  "shushing": ["sussurrando", "silenciando"],
  "siblings": ["irmaos", "irmas"],
  "side ponytail": ["cabelo lateral", "cabelo preso lateralmente"],
  "side-tie panties": ["cueiros laterais"],
  "sideboob": ["mama lateral"],
  "sideburns": ["cabelo lateral", "cabelo de lado"],
  "sidelocks": ["cabelos laterais"],
  "sideways": ["de lado"],
  "sign": ["sinal"],
  "silhouette": ["silhueta"],
  "simple background": ["fundo simples", "fundo basico", "fundo minimalista"],
  "simplified chinese text": ["texto chines simplificado"],
  "single braid": ["cachos soltos", "cachos individuais"],
  "single glove": ["luva unica"],
  "single hair bun": ["coque solto", "coque simples"],
  "single horn": ["unica corneta"],
  "single thighhigh": ["calca de meia perna"],
  "sisters": ["irmas"],
  "sitting": ["sentado"],
  "skeleton": ["esqueleto"],
  "skirt": ["shorts", "saia", "calca curta"],
  "skull": ["cranio"],
  "sky": ["ceu"],
  "sleeping": ["dormindo"],
  "sleeveless": ["sem mangas", "mangas curtas"],
  "sleeveless dress": ["vestido sem mangas"],
  "sleeveless shirt": ["camisa sem mangas"],
  "sleeves past fingers": ["mangas passando pelas maos"],
  "sleeves past wrists": ["saiu do pulso", "sob o pulso", "sobrando pulso"],
  "sleeves rolled up": ["mangas arremessadas"],
  "sliding doors": ["portas deslizantes"],
  "slime (creature)": ["slime", "ser slime"],
  "slime (substance)": ["liquido viscoso", "substancia viscosa"],
  "slime girl": ["garota slime"],
  "slit pupils": ["pupila cortada"],
  "smile": ["sorrindo", "sorriso"],
  "smoke": ["fumaca"],
  "smoking": ["fumando"],
  "smug": ["satisfeito", "arrogante"],
  "sneakers": ["tenis"],
  "snow": ["neve", "nevando"],
  "snowing": ["nevando"],
  "socks": ["meias", "calcas de meias"],
  "soles": ["plantas dos pes"],
  "solo": ["sozinho", "uma pessoa"],
  "solo focus": ["foco unico"],
  "song name": ["nome da musica"],
  "soup": ["sopa"],
  "space": ["espaco"],
  "space helmet": ["casco espacial"],
  "spacecraft": ["nave espacial"],
  "sparkle": ["brilho", "brilhante"],
  "sparkling eyes": ["olhos brilhantes"],
  "sparks": ["fulguracoes", "chispas", "relampagos"],
  "spear": ["lanca"],
  "spiked collar": ["colar espinhoso", "colar com espinhos"],
  "spiked hair": ["cabelo espetado", "cabelo com pontas afiadas", "cabelo com pontas espetadas"],
  "spikes": ["espinhos", "picos"],
  "spoon": ["colher"],
  "spot color": ["cor de ponto"],
  "spotlight": ["luz de spot", "luz de foco", "luz de destaque"],
  "spread arms": ["abrindo os bracos"],
  "spread wings": ["asas abertas", "asas estendidas", "asas abertas largamente"],
  "squatting": ["sentado em posicao baixa", "sentado com pernas cruzadas"],
  "staff": ["funcionario", "empregado"],
  "stage": ["cenario", "palco"],
  "stained glass": ["vitrais"],
  "stairs": ["escada", "ladeira", "passarela"],
  "stand (jojo)": ["stand", "personagem de jojo"],
  "standing": ["em pe"],
  "star (sky)": ["estrela", "estrela no ceu", "estrela no firmamento"],
  "star (symbol)": ["estrela", "estrela simbolo"],
  "star hair ornament": ["adorno de cabelo estrela", "adorno de cabelo com estrela"],
  "starry sky": ["ceu estrelado"],
  "statue": ["estatua", "escultura"],
  "steam": ["vapor"],
  "steam censor": ["censoria vapor", "censoria de vapor"],
  "stick": ["bastao"],
  "still life": ["vitrine", "escenografia"],
  "stitches": ["costuras"],
  "stomach": ["abdomen"],
  "stone floor": ["piso de pedra", "pedra", "chao de pedra"],
  "stone wall": ["parede de pedra"],
  "stool": ["cadeira", "banquinho"],
  "straight hair": ["cabelos lisos"],
  "straight-on": ["de frente"],
  "strangling": ["estrangulando", "apertando"],
  "strapless": ["sem alca", "sem cinto"],
  "strapless dress": ["vestido sem alca", "vestido", "vestidos"],
  "streaked hair": ["cabelo estilizado", "cabelo com riscos", "cabelo com faixas"],
  "street": ["rua"],
  "string": ["fio"],
  "string of fate": ["fio do destino"],
  "string of flags": ["fitilhos de bandeiras"],
  "striped bow": ["cinto listrado", "faixa listrada"],
  "striped clothes": ["roupas listradas"],
  "striped headwear": ["cabeca com listras"],
  "striped pants": ["calcas listradas"],
  "striped pantyhose": ["meias-calcas listradas"],
  "striped scarf": ["lenco listrado", "lenco estampado"],
  "striped shirt": ["camisa listrada", "camisa estrelinha", "camisa estripada"],
  "striped thighhighs": ["calcas de perna alta estriadas", "calcas de perna alta com listras"],
  "strongman waist": ["cintura de homem forte", "cintura musculosa"],
  "stubble": ["bigode"],
  "stuffed animal": ["brinquedo de peluche", "peluche", "brinquedo de pelucia"],
  "stuffed toy": ["brinquedo enfeitado"],
  "style parody": ["parodia de estilo"],
  "subtitled": ["legenda"],
  "suit": ["saiu"],
  "sun": ["sol", "raio solar"],
  "sunbeam": ["raio solar", "raio de sol"],
  "sunglasses": ["oculos de sol", "oculos escuros", "lentes de sol"],
  "sunlight": ["luz do sol", "raio de sol"],
  "sunset": ["por do sol", "entardecer"],
  "suspenders": ["cinto de gravata"],
  "sweat": ["suando", "transpirando"],
  "sweatdrop": ["gotinha de suor"],
  "swept bangs": ["cabelos de lado", "cabelos arrepiados"],
  "swimming": ["nadar", "banho", "banho de piscina"],
  "swimsuit": ["biquini"],
  "sword": ["espada"],
  "sword on back": ["espada no ombro", "espada na cintura"],
  "symbol-shaped pupils": ["pupila simbolica", "pupila simbolo"],
  "t-shirt": ["camiseta"],
  "tabi": ["meias-calcas-de-tabi"],
  "table": ["mesa", "tabela"],
  "tail": ["cauda"],
  "tank top": ["top de moletom"],
  "tassel": ["pendente"],
  "tatami": ["tatame", "tapete de bambu", "tapete japones"],
  "tattoo": ["tatuagem"],
  "tea": ["cha"],
  "teacup": ["cha", "xicara de cha"],
  "teapot": ["cha", "caneca de cha"],
  "tears": ["lagrimas", "chorando"],
  "teeth": ["dentes"],
  "tent": ["tenda"],
  "tentacles": ["tentaculos"],
  "text focus": ["texto em foco", "texto principal", "texto focado"],
  "thick eyebrows": ["sobrancelhas grossas"],
  "thick mustache": ["bigode grosso", "bigode espesso", "bigode denso"],
  "thigh boots": ["botas de coxa", "botas de perna"],
  "thighhighs": ["calcas ate a coxa"],
  "thighs": ["pernas", "coxas"],
  "third eye": ["terceiro olho"],
  "thorns": ["espinhos"],
  "throne": ["trono"],
  "thumbs up": ["cara de aprovacao", "polegar para cima"],
  "tile floor": ["piso de ceramica", "piso de azulejos"],
  "tiptoes": ["pes levantados", "pes em ponta"],
  "title": ["titulo", "nome", "nome do livro"],
  "toenail polish": ["esmalte de unha dos pes", "esmalte para unhas dos pes"],
  "toenails": ["unha do pe", "unhas dos pes"],
  "toes": ["dedos dos pes", "dedinhos dos pes"],
  "tombstone": ["tumulo"],
  "tongue": ["lingua"],
  "tongue out": ["lingua para fora", "lingua de fora"],
  "top hat": ["chapeu alto", "chapeu", "chapeus"],
  "topknot": ["cabeca de touca", "cabeca de topknot"],
  "topless male": ["homem sem camisa", "homem nu acima do quadril"],
  "torch": ["torcheira", "candeia"],
  "torii": ["portao japones", "portao de madeira"],
  "torn clothes": ["roupas rasgadas"],
  "towel": ["toalha"],
  "towel around neck": ["lenco no pescoco", "lenco ao redor do pescoco", "lenco colocado no pescoco"],
  "towel on head": ["toalha no cabelo", "toalha na cabeca"],
  "tower": ["torre"],
  "town": ["vila", "cidade pequena"],
  "track jacket": ["jaca de corrida"],
  "track suit": ["trico"],
  "traditional media": ["midia tradicional"],
  "transparent": ["translucido"],
  "trash bag": ["sacola de lixo"],
  "tray": ["prato", "trincadeira"],
  "tree": ["arvore"],
  "trembling": ["tremendo", "tremendo de medo"],
  "turban": ["turbante"],
  "turtleneck": ["colarinho de gola alta"],
  "tusks": ["dentes de rinoceronte"],
  "twin braids": ["cabelos em trancas"],
  "twin drills": ["ouvidos gemeos"],
  "twins": ["gemeos"],
  "twintails": ["cabelos em duas caudas", "cabelos em cauda de cavalo"],
  "two side up": ["duas laterais levantadas"],
  "two-sided cloak": ["capa de dois lados", "capa dobravel"],
  "two-tone hair": ["cabelo de dois tons"],
  "umbrella": ["parasol"],
  "under covers": ["coberto"],
  "under-rim eyewear": ["lentes de oculos sob o rim"],
  "undercut": ["corte de cabelo curto", "corte de cabelo baixo"],
  "underwater": ["submarino"],
  "underwear": ["sutia", "calcinha", "cueiro"],
  "uneven legwear": ["vestuario das pernas desiguais"],
  "uniform": ["uniforme"],
  "unsheathing": ["desembainhando", "retirando"],
  "unworn boots": ["botas sem usar"],
  "unworn hat": ["chapeu sem usar"],
  "unworn headwear": ["cabeca sem chapeu"],
  "unworn helmet": ["chapeleiro nao usado", "chapeleiro vazio"],
  "unworn mask": ["mascara nao usada"],
  "updo": ["penteados de cima", "penteados elevados"],
  "upper body": ["meio corpo", "busto"],
  "upper teeth only": ["dentes superiores"],
  "upside-down": ["inverso", "de cabeca para baixo"],
  "ushanka": ["chapeu ushanka"],
  "v-shaped eyebrows": ["sobrancelhas em v", "sobrancelhas v"],
  "vampire": ["vampiro"],
  "vase": ["vaso", "jarra", "vaso de flores"],
  "vegetable": ["legume", "vegetal", "verdura"],
  "vehicle focus": ["foco em veiculos", "veiculos"],
  "veil": ["venda", "venda facial"],
  "vertical-striped clothes": ["roupas listradas verticalmente", "camiseta listrada verticalmente"],
  "very long hair": ["cabelo muito longo"],
  "very short hair": ["cabelo muito curto"],
  "very wide shot": ["quadro muito largo", "quadro amplo"],
  "vest": ["jaleco", "blusa"],
  "village": ["vila"],
  "vines": ["ampulheta"],
  "virtual youtuber": ["youtuber virtual"],
  "walking": ["andando", "caminhando"],
  "wand": ["varinha"],
  "wariza": ["personagem wariza"],
  "water": ["agua"],
  "watercraft": ["barco", "navio", "lancha"],
  "waterfall": ["cascata"],
  "waves": ["ondas"],
  "waving": ["agitando", "agitando-se"],
  "wavy mouth": ["boca ondulada", "boca ondosa", "sorriso ondulado"],
  "weapon": ["arma"],
  "weapon on back": ["arma nas costas", "arma no ombro", "arma atras"],
  "weapon over shoulder": ["arma sobre o ombro", "arma em cima do ombro"],
  "wet": ["molhado"],
  "wheat": ["trigo"],
  "whiskers": ["bigode", "barba"],
  "white apron": ["apron branco"],
  "white ascot": ["ascota branca"],
  "white background": ["fundo branco"],
  "white bow": ["laco branco"],
  "white cape": ["capa branca"],
  "white capelet": ["capa branca", "blusa branca"],
  "white choker": ["colar branco", "colar de pescoco"],
  "white coat": ["blusa branca"],
  "white dress": ["vestido branco", "vestido de noiva", "vestido de casamento"],
  "white eyes": ["olhos brancos"],
  "white flower": ["flor branca", "flores brancas"],
  "white footwear": ["calcado branco"],
  "white fur": ["pelucia branca"],
  "white gloves": ["luvas brancas", "luvas de algodao", "luvas de seda"],
  "white hair": ["cabelo branco"],
  "white headwear": ["cabeleira branca", "cabeleira branca de personagem"],
  "white hoodie": ["hoodie branco"],
  "white jacket": ["jacket branco", "jaleco branco"],
  "white kimono": ["kimono branco", "roupa branca"],
  "white panties": ["calcinhas brancas", "calcinha branca", "calcinhas"],
  "white pants": ["calcas brancas"],
  "white pupils": ["pupila branca"],
  "white ribbon": ["faixa branca"],
  "white robe": ["roupa branca", "vestido branco", "blusa branca"],
  "white sailor collar": ["colarinho branco", "colarinho marinheiro"],
  "white sash": ["faixa branca"],
  "white scarf": ["lenco branco"],
  "white shirt": ["camisa branca"],
  "white shorts": ["shorts brancos"],
  "white skirt": ["saia branca"],
  "white sweater": ["sweater branco", "sueter branco"],
  "white wings": ["as brancas"],
  "wide shot": ["quadro amplo"],
  "wide sleeves": ["mangas largas"],
  "wide-eyed": ["olhos arregalados"],
  "wind": ["vento"],
  "window": ["janela"],
  "window blinds": ["persianas"],
  "wine": ["vinho"],
  "wine glass": ["copo de vinho"],
  "wing collar": ["colarinho com asas"],
  "winged helmet": ["capacete com asas"],
  "wings": ["asas"],
  "winter": ["inverno", "tempo frio"],
  "winter clothes": ["roupas de inverno", "trajes de inverno", "roupas frio"],
  "wisteria": ["vime"],
  "witch hat": ["chapeu de bruxa", "chapeu de feiticeira", "chapeu de bruxa tradicional"],
  "wolf": ["lobo"],
  "wolf boy": ["garoto lobo"],
  "wolf ears": ["ouvidos de lobo"],
  "wood": ["madeira", "tronco", "troncos"],
  "wooden floor": ["chao de madeira"],
  "wooden sword": ["espada de madeira"],
  "wooden table": ["mesa de madeira", "mesa", "madeira"],
  "wooden wall": ["parede de madeira"],
  "wrinkled skin": ["pele com rugas"],
  "wristband": ["bracelete", "bracelete de pulso"],
  "writing": ["escrita"],
  "x hair ornament": ["adorno de cabelo", "pulseira de cabelo"],
  "yaoi": ["shounen-ai"],
  "yellow background": ["fundo amarelo"],
  "yellow dress": ["vestido amarelo"],
  "yellow eyes": ["olhos amarelos"],
  "yellow flower": ["flor amarela"],
  "yellow scarf": ["lenco amarelo", "lenco dourado"],
  "yellow shirt": ["camisa amarela"],
  "yellow sky": ["ceu amarelo"],
  "yellow theme": ["tema amarelo", "amarelo"],
  "yin yang": ["simbolo yin yang"],
  "zombie": ["zumbi"],
}
